import org.junit.*;
import java.util.*;
import play.test.*;
import models.*;

public class ModelTest extends UnitTest {
    @Before
    public void setUp () {
        // clear the db
        Fixtures.deleteAll();
        Fixtures.loadModels("relationships.yml");
    }

    @Test
    public void testInstatiation () {
        
    }

    @Test
    public void testMetroAreaToString () {
        // TODO: assuming the autogenerated IDs are sequential from 0 isn't safe. Something
        // must be done.
        MetroArea sf = MetroArea.find("byName", "San Francisco-Oakland-San José, CA").first();
        MetroArea empty = MetroArea.find("byId", 1L).first();
        MetroArea full = NtdAgency.find("byWebsite", "http://metro.kingcounty.gov").first()
            .metroArea;
        MetroArea fullNoAgencyName = NtdAgency.find("byWebsite", "http://example.com").first()
            .metroArea;
        assertEquals("San Francisco-Oakland-San José, CA", sf.toString());
        //        assertEquals("Empty metro area", empty.toString());
        assertEquals("Metro including King County Metro", full.toString());
        assertEquals("Metro including http://example.com", fullNoAgencyName.toString());
    }

    @Test
    public void testAgencyFeedRelation () {
        NtdAgency bart = NtdAgency.find("byWebsite", "http://bart.gov").first();
        NtdAgency kcm = NtdAgency.find("byWebsite", "http://metro.kingcounty.gov").first();

        assertEquals(2, bart.feeds.size());
        assertEquals(2, kcm.feeds.size());
        
        // test that the feeds are allocated correctly and that the shared feed is shared
        GtfsFeed[] bartGtfs = new GtfsFeed[2];
        GtfsFeed[] kcmGtfs = new GtfsFeed[2];
        bart.feeds.toArray(bartGtfs);
        kcm.feeds.toArray(kcmGtfs);

        // this is the combined GTFS
        assertEquals(bartGtfs[1], kcmGtfs[1]);
        assertEquals("http://www.bart.gov", bartGtfs[0].agencyWebsite);
        assertEquals("http://metro.kingcounty.gov", kcmGtfs[0].agencyWebsite);
    }
}
